export default {
  events: [
    {
      id: 1,
      day: 'samedi',
      hour: '13h30 - 14h',
      title: 'Accueil des participants - café',
      resume: '',
      content: '',
      speaker: [],
      room: 'Hall d\'accueil',
      type: 'administratif',
      fav: false
    },
    {
      id: 2,
      day: 'samedi',
      hour: '14h - 14h30',
      title: 'Mot de bienvenue',
      resume: 'Introduction du week-end par Poitiers Collectif',
      content: '',
      speaker: ['Poitiers Collectif'],
      room: 'Amphi Carbonnier',
      type: 'conference',
      fav: false
    },
    {
      id: 3,
      day: 'samedi',
      hour: '14h30 - 16h00',
      title: 'Plénière',
      resume: 'Le municipalisme, un levier pour réenchanter la politique par la proximité ?',
      content: '',
      speaker: ['Fanny Lacroix', 'Christian Proust'],
      room: 'Amphi Carbonnier',
      type: 'conference',
      fav: false
    },
    {
      id: 4,
      day: 'samedi',
      hour: '16h15 - 18h00',
      title: 'Speed dating des démarches citoyennes',
      resume: 'Vous avez des interrogations ? Il vous manque des informations ? On se donne tous des solutions',
      content: 'Discussions entre les différentes initiatives présentes pour répondre aux problématiques de chacun. Puis restitution commune pour des solutions collectives.',
      speaker: ['Tous Elus', 'La Bascule', 'Poitiers Collectif'],
      room: 'Salles 11-12-13-14',
      type: 'atelier',
      fav: false
    },
    {
      id: 5,
      day: 'samedi',
      hour: '18h15 - 19h45',
      title: 'Retour d\'expérience de Saillans & simulation d\'une élection sans candidat',
      resume: '',
      content: 'Tristan Rechid revient sur l\'expérience de liste citoyenne et de gestion de commune citoyenne de Saillans. Il s\'en suivra une simulation d\'élection sans candidat avec Poitiers Collectif.',
      speaker: ['Tristan Rechid', 'Démocraties vivantes'],
      room: 'Amphi Carbonnier',
      type: 'conference',
      fav: false
    },
    {
      id: 6,
      day: 'samedi',
      hour: '20h00 - 20h50',
      title: 'Action publique devant l\'hotel de ville',
      resume: '',
      content: 'On part sur la place publique faire entendre notre voix !',
      speaker: ['Tous Elus'],
      room: 'Place maréchal Leclerc',
      type: 'divertissement',
      fav: false
    },
    {
      id: 7,
      day: 'samedi',
      hour: '21h00 - 23h00',
      title: 'Soirée conviviale',
      resume: 'Un repas et des surprises pour mieux faire connaissance, échanger, partager.',
      content: '',
      speaker: [],
      room: 'Salle Waline',
      type: 'divertissement',
      fav: false
    },
    {
      id: 8,
      day: 'dimanche',
      hour: '9h00 - 9h20',
      title: 'Accueil - café',
      resume: 'On s\'y remet en douceur',
      content: '',
      speaker: [],
      room: 'Hall d\'accueil',
      type: 'divertissement',
      fav: false
    },
    {
      id: 9,
      day: 'dimanche',
      hour: '9h30 - 11h30',
      title: 'Atelier - session 1',
      resume: 'Mobiliser des profils jeunes et éloignés de la politique pour les municipales',
      content: [],
      speaker: ['Tous Elus'],
      room: 'Salle 11',
      type: 'atelier',
      fav: false
    },
    {
      id: 10,
      day: 'dimanche',
      hour: '9h30 - 11h30',
      title: 'Atelier - session 1',
      resume: 'Listes participatives : le label haute qualité démocratique pour s\'auto-évaluer, progresser et distinguer le vrai du faux.',
      content: '',
      speaker: ['La belle démocratie', 'Christian Proust'],
      room: 'Salle 12',
      type: 'atelier',
      fav: false
    },
    {
      id: 11,
      day: 'dimanche',
      hour: '9h30 - 11h30',
      title: 'Atelier - session 1',
      resume: 'La plateforme décidim : savoir utiliser le numérique pour communiquer son projet et dialoguer avec les citoyens.',
      content: '',
      speaker: ['Action Commune', 'Open source politics'],
      room: 'Salle 13',
      type: 'atelier',
      fav: false
    },
    {
      id: 12,
      day: 'dimanche',
      hour: '9h30 - 11h30',
      title: 'Atelier - session 1',
      resume: 'Frapper aux portes pour gagner les élections ? Initiation aux techniques de ciblage et tractage.',
      content: '',
      speaker: ['À Nous la démocratie !'],
      room: 'Salle 14',
      type: 'atelier',
      fav: false
    },
    {
      id: 13,
      day: 'dimanche',
      hour: '9h30 - 11h30',
      title: 'Atelier - session 1',
      resume: 'Démarrer et s\'engager dans une démarche de transition citoyenne, écologique, solidaire adaptée à son territoire : le pacte pour la transition',
      content: '',
      speaker: ['La Bascule'],
      room: 'Salle Waline',
      type: 'atelier',
      fav: false
    },
    {
      id: 14,
      day: 'dimanche',
      hour: '11h45 - 13h00',
      title: 'Plénière',
      resume: 'Ecologie, démocratie : même combat ? Faire s’engager les élus et les citoyens pour la transition démocratique, écologique et sociale.',
      content: '',
      speaker: ['Charles Fournier', 'Charlotte Marchandise'],
      room: 'Amphi Carbonnier',
      type: 'conference',
      fav: false
    },
    {
      id: 15,
      day: 'dimanche',
      hour: '13h00 - 13h45',
      title: 'Déjeuner',
      resume: 'Une petite pause restauration ne fera pas de mal :).',
      content: '',
      speaker: [],
      room: 'Salle Waline',
      type: 'divertissement',
      fav: false
    },
    {
      id: 15,
      day: 'dimanche',
      hour: '14h00 - 16h00',
      title: 'Ateliers - session 2',
      resume: 'Quelles stratégies et quels outils de communication digitale (sites web, réseaux sociaux...) pour faire une campagne numérique efficace',
      content: '',
      speaker: ['Tous Elus'],
      room: 'Salle 11',
      type: 'atelier',
      fav: false
    },
    {
      id: 16,
      day: 'dimanche',
      hour: '14h00 - 16h00',
      title: 'Ateliers - session 2',
      resume: 'Listes participatives et organisations politiques : comment "faire avec" ?',
      content: '',
      speaker: ['La belle démocratie', 'Charles Fournier'],
      room: 'Salle 12',
      type: 'atelier',
      fav: false
    },
    {
      id: 16,
      day: 'dimanche',
      hour: '14h00 - 16h00',
      title: 'Ateliers - session 2',
      resume: 'Mobiliser dans les quartiers et créer des dynamiques collectives autour de la campagne avec la méthode Alinsky',
      content: '',
      speaker: ['Action Commune', 'Institu Alinsky'],
      room: 'Salle 13',
      type: 'atelier',
      fav: false
    },
    {
      id: 17,
      day: 'dimanche',
      hour: '14h00 - 16h00',
      title: 'Ateliers - session 2',
      resume: 'Faire vivre la démocratie directe à l\'échelle municipale : la question institutionnelle dans la constitution des programmes citoyens',
      content: '',
      speaker: ['À Nous la démocratie !'],
      room: 'Salle 14',
      type: 'atelier',
      fav: false
    },
    {
      id: 18,
      day: 'dimanche',
      hour: '14h00 - 16h00',
      title: 'Ateliers - session 2',
      resume: 'Miser sur un outil ludique, participatif et créatif sur le changement climatique : la fresque pour le climat',
      content: '',
      speaker: ['La Bascule'],
      room: 'Salle Waline',
      type: 'atelier',
      fav: false
    },
    {
      id: 18,
      day: 'dimanche',
      hour: '16h15',
      title: 'Mot de clôture',
      resume: '',
      content: '',
      speaker: ['Poitiers Collectif'],
      room: 'Amphi Carbonnier',
      type: 'conference',
      fav: false
    }
  ]
}
